apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: ms-platform-integration-services

labels:
- pairs:
    environment: prod

resources:
- install-rabbitmq-alerts-prod.yml
- install-rabbit-metrics-prod.yml

