apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      environment: uat
      k8s-app: rmq-uat-monitor
      priority: med
      role: monitoring
      template: monitoring-metrics-publisher-template_v1
    name: rmq-uat-monitor
    namespace: ms-uat-platform-integration-services
  spec:
    endpoints:
    - interval: 30s
      port: prometheus
      scheme: http
    selector:
      matchLabels:
        app.kubernetes.io/name: uat-rmq
kind: List
metadata: {}
