apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: ms-uat-platform-integration-services

labels:
- pairs:
    environment: uat
    
resources:
- install-rabbitmq-alerts-uat.yml
- install-rabbit-metrics-uat.yml