apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: ms-dev-platform-integration-services

labels:
- pairs:
    environment: dev
    
resources:
- install-rabbitmq-alerts-dev.yml
- install-rabbit-metrics-dev.yml