apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: prod-rabbit-alerts
  namespace: ocp-cluster-config
  annotations:
    apps.open-cluster-management.io/deployables: ""
    apps.open-cluster-management.io/subscriptions: ocp-cluster-config/prod-rabbit-alerts-subscription-1,ocp-cluster-config/prod-rabbit-alerts-subscription-1-local
    open-cluster-management.io/user-group: c3lzdGVtOnNlcnZpY2VhY2NvdW50cyxzeXN0ZW06c2VydmljZWFjY291bnRzOm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LHN5c3RlbTphdXRoZW50aWNhdGVk
    open-cluster-management.io/user-identity: c3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50Om11bHRpY2x1c3Rlci1hcHBsaWNhdGlvbnM=
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - prod-rabbit-alerts
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: prod-rabbit-alerts-subscription-1
  namespace: ocp-cluster-config
  annotations:
    apps.open-cluster-management.io/cluster-admin: "true"
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-current-commit: ee3b1db06f92f3e656f79f5d350aa432b0bfa13a
    apps.open-cluster-management.io/git-path: ms-platform-main/openshift/acm/deployments/config/monitoring/rabbitmq/overlays/prod
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: prod-rabbit-alerts
    app.kubernetes.io/part-of: prod-rabbit-alerts
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: github.com/nikhilgupta3/testrepo
  placement:
    placementRef:
      name: prod-rabbit-alerts-placement-1
      kind: PlacementRule
posthooks: {}
prehooks: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prod-rabbit-alerts-placement-1
  namespace: ocp-cluster-config
  annotations:
  labels:
    app: prod-rabbit-alerts
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
