apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    labels:
    name: platform-alert-node
    namespace: openshift-monitoring
  spec:
    groups:
    - name: platform-alert-node-disk_limit
      rules:
      - alert: platform-alert-node-disk_limit
        annotations:
          description: 'Disk space consumed more than 80%: {{ $value }}'
          summary: Disk space a warning level
        expr: 100 - ((node_filesystem_free_bytes{mountpoint="/",fstype!="rootfs"}
          * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) >
          80
        labels:
          severity: warning
      - alert: platform-alert-node-disk_limit
        annotations:
          description: 'Disk space consumed more than 95%: {{ $value }}'
          summary: Disk space a critical levels
        expr: 100 - ((node_filesystem_free_bytes{mountpoint="/",fstype!="rootfs"}
          * 100) / node_filesystem_size_bytes{mountpoint="/",fstype!="rootfs"}) >
          95
        labels:
          severity: critical
    - name: platform-alert-backup-etcd
      rules:
      - alert: platform-alert-backup-etcd
        annotations:
          description: Backup of ETCD has failed
          summary: Backup of Master ETCD has failed on one or more Master nodes.
        expr: max(kube_job_failed{condition="true",namespace="ocp-backup"} * ON(job_name)
          GROUP_RIGHT()  kube_job_status_start_time) BY (value) == max(kube_job_status_start_time{namespace="ocp-backup"})
          BY (value)
        labels:
          severity: warning
      - alert: platform-alert-backup-etcd
        annotations:
          description: 'Disk space consumed more than 95%: {{ $value }}'
          summary: Backup of Master ETCD has failed on one or more Master nodes.
        expr: max(kube_job_failed{condition="true",namespace="ocp-backup"} * ON(job_name)
          GROUP_RIGHT()  kube_job_status_start_time) BY (value) == max(kube_job_status_start_time{namespace="ocp-backup"})
          BY (value)
        for: 6h
        labels:
          severity: critical
kind: List
metadata: {}
