apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
- ../../base

namespace:  openshift-monitoring

labels:
- pairs:
    priority: med
    role: monitoring
    
resources:
- install-platform-alerts.yml
